# Generated by Django 2.2.5 on 2019-09-09 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(choices=[('csps', 'CSPS'), ('ilab', 'I-LAB'), ('ins', 'INS'), ('ocio', 'OCIO'), ('aps', 'APS'), ('dac', 'DAC'), ('eai', 'EAI'), ('a2i', 'A2I')], max_length=100)),
                ('superieur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status_demande', models.CharField(blank=True, choices=[('accepte', 'ACCEPTE'), ('refusee', 'REFUSEE'), ('en_attente', 'EN ATTENTE')], max_length=100, null=True)),
                ('validation_securite', models.BooleanField(default=False)),
                ('validation_hierarchique', models.BooleanField(default=False)),
                ('validation_admin', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('demandeur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to=settings.AUTH_USER_MODEL)),
                ('validateur_hierarchique', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_agents', to=settings.AUTH_USER_MODEL)),
                ('validateur_securite', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_recues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
