# Generated by Django 2.2.5 on 2019-09-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='date_expiration',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
