# Generated by Django 2.2.5 on 2019-09-09 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190909_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='validateur_hierarchique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demande',
            name='validateur_securite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_recues', to=settings.AUTH_USER_MODEL),
        ),
    ]
