# Generated by Django 2.2.5 on 2019-09-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190909_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_demande', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
