# Generated by Django 2.2.5 on 2019-09-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_protocole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocole',
            old_name='status_demande',
            new_name='libelle',
        ),
    ]
