# Generated by Django 2.2.5 on 2019-09-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190909_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='Protocoles',
            field=models.ManyToManyField(to='api.Protocole'),
        ),
    ]
