# Generated by Django 2.2.5 on 2019-09-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_demande_protocoles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='Protocoles',
            new_name='protocoles',
        ),
    ]
