# Generated by Django 2.2.5 on 2019-09-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190909_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='protocoles',
            field=models.ManyToManyField(to='api.Protocole'),
        ),
    ]
