# Generated by Django 2.2.5 on 2019-09-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190909_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='protocoles',
        ),
        migrations.AddField(
            model_name='demande',
            name='protocoles',
            field=models.CharField(blank=True, choices=[('http', 'HTTP'), ('https', 'HTPPS'), ('tcp', 'TCP'), ('ip', 'IP')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Protocole',
        ),
    ]
