# Generated by Django 2.2.5 on 2019-09-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190909_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='protocoles',
        ),
    ]
