# Generated by Django 2.2.5 on 2019-09-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_demande_protocoles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='demande',
            name='protocoles',
        ),
        migrations.AddField(
            model_name='demande',
            name='protocoles',
            field=models.ManyToManyField(to='api.Protocole'),
        ),
    ]
