# Generated by Django 2.2.5 on 2019-09-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190910_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='status',
            field=models.CharField(default='En attente de la validation du supérieur hierarchique', max_length=100),
        ),
    ]
