# Generated by Django 2.2.5 on 2019-09-11 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_demande_status_demande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='status',
            new_name='status_demande',
        ),
    ]
