# Generated by Django 2.2.5 on 2019-09-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20190911_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='addresse_ip',
            new_name='adresse_ip',
        ),
    ]
