# Generated by Django 2.2.5 on 2019-09-13 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0026_auto_20190913_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='beneficiaire',
        ),
        migrations.AddField(
            model_name='demande',
            name='beneficiaire',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
