# Generated by Django 2.2.5 on 2019-09-13 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20190913_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='beneficiaire',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
