# Generated by Django 2.2.5 on 2019-09-13 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0028_auto_20190913_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='beneficiaire',
        ),
        migrations.AddField(
            model_name='demande',
            name='beneficiaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
